theme: jekyll-theme-minimal
title: [The title of your site]
description: [A short description of your site's purpose]
logo: [cat](https://static.toiimg.com/thumb/msid-67586673,width-800,height-600,resizemode-75,imgsize-3918697,pt-32,y_pad-40/67586673.jpg)
show_downloads: "false"
