# Site
repository: vmulholl/vmulholl.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Conrad Harmse
title: Aspiring Equity Analyst
email: conrad.harmse38@gmail.com
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mianzo Asset Management
        link: https://www.mianzo.co.za/
        link_text: mianzo.co.za
        sub_title: ADJECTIVE (ex. pension fund investiment market) Job Shadowing
        caption: November 2017 - Present
        quote: >
          Building long-term wealth through management of assets on behalf of clients, including preservation and creation of assets.
        description: | # this will include new lines to allow paragraphs
            Gained valuable insights in day-to-day workings of (NUMBER OF PEOPLE SHADOWED) surrounding pension fund and other institutional investment industries, as well as being exposed to hedging methodology in this environment.
      - layout: left
        title: Reitway Global
        link: https://www.reitwayglobal.com/
        link_text: reitwayglobal.com
        sub_title: Job Shadowing
        caption: November 2017 - Present
        quote: >
          To be the leading Global Listed Property asset manager dedicated to delivering superior performance
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Deon Harmse (Compliance Officer)
        link: https://www.mianzo.co.za/
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Stellenbosch University
        caption: 2019
        sub_title: BComHons Financial Economics
        quote: >
          Amongst South Africa's leading tertiary institutions based on research output, student pass rates and rated scientists, and is recognised internationally as an academic institution of excellence.
        description: | # this will include new lines to allow paragraphs
          l.

      - layout: left
        title: Stellenbosch University
        caption: 2016 - 2018
        sub_title: BCom Investment management
        description: | # this will include new lines to allow paragraphs
          Covered both levels 1 and 2 of the CFA Insitute's curriculum
          
          Advanced competencies in the basic Microsoft suite (Excel, Word, etc.)
          
          Fondations in various analytical programming languages (R, S___)
          
          Worked with several public datasets and produced numerous professional academic essays

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in equity management and technology:
      - Surfing
      - Bros
      - Knitting
      - Kayaking with my cool brother in the ocean
      
      Look at this cool image of my bro

      ![CoolBro](images/coolbro.jpg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
